x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '2020.3.1'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.

  clusterConstraints:
    resources:
    - requests:
        cpu: 8000m
        memory: 32Gi

  images: 
    '':
      properties:
        appviewx.image.repository:
          type: REPO_WITH_REGISTRY
        appviewx.image.tag:
          type: TAG
    mongo-init:
      properties:
        mongodb.image.registry:
          type: REGISTRY
        mongodb.image.repository:
          type: REPO_WITHOUT_REGISTRY
        mongodb.image.tag:
          type: TAG
    avx-cloud-mongoseed:
      properties:
        mongodbseed.image.registry:
          type: REGISTRY
        mongodbseed.image.repository:
          type: REPO_WITHOUT_REGISTRY
        mongodbseed.image.tag:
          type: TAG
    avx-cloud-managedservice:
      properties:
        avx-config-server.image.registry:
          type: REGISTRY
        avx-config-server.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-config-server.image.tag:
          type: TAG
        avx-commons.image.registry:
          type: REGISTRY
        avx-commons.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-commons.image.tag:
          type: TAG
        avx-platform-core.image.registry:
          type: REGISTRY
        avx-platform-core.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-platform-core.image.tag:
          type: TAG
        avx-platform-queue.image.registry:
          type: REGISTRY
        avx-platform-queue.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-platform-queue.image.tag:
          type: TAG 
        avx-crontab.image.registry:
          type: REGISTRY
        avx-crontab.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-crontab.image.tag:
          type: TAG
        avx-subsystems.image.registry:
          type: REGISTRY
        avx-subsystems.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-subsystems.image.tag:
          type: TAG
        avx-vendors.image.registry:
          type: REGISTRY
        avx-vendors.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-vendors.image.tag:
          type: TAG
        avx-vendor-cert-scep-agent.image.registry:
          type: REGISTRY
        avx-vendor-cert-scep-agent.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-vendor-cert-scep-agent.image.tag:
          type: TAG
        avx-vendor-cert-est-agent.image.registry:
          type: REGISTRY
        avx-vendor-cert-est-agent.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-vendor-cert-est-agent.image.tag:
          type: TAG
        avx-vendor-cert-network-discovery.image.registry:
          type: REGISTRY
        avx-vendor-cert-network-discovery.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-vendor-cert-network-discovery.image.tag:
          type: TAG
    avx-cloud-gateway:
      properties:
        avx-platform-gateway.image.registry:
          type: REGISTRY
        avx-platform-gateway.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-platform-gateway.image.tag:
          type: TAG
    avx-cloud-web:
      properties:
        avx-platform-web.image.registry:
          type: REGISTRY
        avx-platform-web.image.repository:
          type: REPO_WITHOUT_REGISTRY
        avx-platform-web.image.tag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

required:
- name
- namespace
